const seededAt = '2026-06-14T00:00:00.000Z'
const bookSource = 'Le design graphique : savoirs & savoir-faire'

const baseChallenge = (input) => ({
  wrongAnswers: [],
  explanation: '',
  difficulty: 'Moyen',
  milestones: 3,
  mode: 'Défi',
  status: 'pending',
  approvals: [],
  tags: ['socle', 'défi'],
  source: 'Socle',
  sourcePage: '',
  revisionNotes: '',
  favorite: false,
  confidence: 1,
  history: [],
  createdAt: seededAt,
  updatedAt: seededAt,
  ...input,
})

export const approvedChallengeQuestions = [
  baseChallenge({
    id: 'APPROVED-BUZZER-001',
    question: "Qu'est-ce que le gris typographique ?",
    answer: 'Un concept qui englobe plusieurs éléments définis pour donner un bon équilibre à une composition',
    wrongAnswers: [
      "L'équilibre d'opacité entre noir et gris pour hiérarchiser les informations",
      'La répartition du texte et des images pour créer un contraste visuel',
    ],
    explanation: "Le gris typographique désigne l'équilibre visuel créé par la densité du texte sur une page.",
    category: 'Composition',
    challengeType: 'Buzzer',
    tags: ['socle', 'défi', 'buzzer'],
  }),
  baseChallenge({
    id: 'APPROVED-BUZZER-002',
    question: 'Quelle est la couleur complémentaire du rouge ?',
    answer: 'Le vert',
    wrongAnswers: ['Le jaune', 'Le violet'],
    explanation: "Dans le cercle chromatique, les couleurs complémentaires sont placées à l'opposé l'une de l'autre.",
    category: 'Signe et couleur',
    challengeType: 'Buzzer',
    tags: ['socle', 'défi', 'buzzer'],
  }),
  baseChallenge({
    id: 'APPROVED-BUZZER-003',
    question: 'Quel raccourci clavier permet de tout sélectionner ?',
    answer: 'Ctrl + A (Cmd + A)',
    wrongAnswers: ['Ctrl + C (Cmd + C)', 'Ctrl + Z (Cmd + Z)'],
    explanation: 'Ce raccourci universel fonctionne dans la plupart des logiciels.',
    category: 'Production',
    challengeType: 'Buzzer',
    tags: ['socle', 'défi', 'buzzer'],
  }),
  baseChallenge({
    id: 'APPROVED-BUZZER-004',
    question: "Qu'est-ce qu'une typographie serif ?",
    answer: 'Une typographie avec empattements',
    wrongAnswers: [
      'Une typographie uniquement en capitales',
      'Une typographie sans contraste de pleins et déliés',
    ],
    explanation: 'Une typographie serif possède des empattements aux extrémités des lettres.',
    category: 'Typographie',
    challengeType: 'Buzzer',
    tags: ['socle', 'défi', 'buzzer'],
  }),

  baseChallenge({
    id: 'APPROVED-VRAIFAUX-001',
    question: 'Le RGB est un modèle de couleur additif utilisé principalement pour les écrans.',
    answer: 'Vrai',
    wrongAnswers: ['Faux'],
    explanation: 'Le RGB, ou RVB, combine des lumières rouge, verte et bleue.',
    category: 'Signe et couleur',
    challengeType: 'Vrai/Faux',
    tags: ['socle', 'défi', 'vrai ou faux'],
  }),
  baseChallenge({
    id: 'APPROVED-VRAIFAUX-002',
    question: "Le CMJN est un mode colorimétrique généralement destiné à l'impression.",
    answer: 'Vrai',
    wrongAnswers: ['Faux'],
    explanation: 'Le CMJN correspond aux encres cyan, magenta, jaune et noir utilisées en impression.',
    category: 'Production',
    challengeType: 'Vrai/Faux',
    tags: ['socle', 'défi', 'vrai ou faux'],
  }),
  baseChallenge({
    id: 'APPROVED-VRAIFAUX-003',
    question: "Le fond perdu sert à éviter un liseré blanc après la coupe d'un document imprimé.",
    answer: 'Vrai',
    wrongAnswers: ['Faux'],
    explanation: 'Le fond perdu prolonge les éléments graphiques au-delà du format final pour sécuriser la découpe.',
    category: 'Production',
    challengeType: 'Vrai/Faux',
    tags: ['socle', 'défi', 'vrai ou faux'],
  }),
  baseChallenge({
    id: 'APPROVED-VRAIFAUX-004',
    question: "Le crénage désigne l'ajustement de l'espace entre deux lettres précises.",
    answer: 'Vrai',
    wrongAnswers: ['Faux'],
    explanation: "Le crénage agit sur une paire de lettres, contrairement à l'interlettrage qui concerne un ensemble plus large.",
    category: 'Typographie',
    challengeType: 'Vrai/Faux',
    tags: ['socle', 'défi', 'vrai ou faux'],
  }),
  baseChallenge({
    id: 'APPROVED-VRAIFAUX-005',
    question: 'La loi de proximité de Gestalt indique que des éléments proches sont perçus comme liés.',
    answer: 'Vrai',
    wrongAnswers: ['Faux'],
    explanation: 'La proximité conduit le regard à regrouper les éléments situés près les uns des autres.',
    category: 'Composition',
    challengeType: 'Vrai/Faux',
    tags: ['socle', 'défi', 'vrai ou faux'],
  }),
  baseChallenge({
    id: 'APPROVED-VRAIFAUX-006',
    question: "Une image destinée à l'impression est souvent préparée autour de 300 DPI.",
    answer: 'Vrai',
    wrongAnswers: ['Faux'],
    explanation: 'Une résolution de 300 DPI est une référence courante pour une impression de qualité.',
    category: 'Production',
    challengeType: 'Vrai/Faux',
    tags: ['socle', 'défi', 'vrai ou faux'],
  }),
  baseChallenge({
    id: 'APPROVED-VRAIFAUX-007',
    question: 'Un logo pérenne est un logo qui suit toujours la dernière tendance graphique.',
    answer: 'Faux',
    wrongAnswers: ['Vrai'],
    explanation: 'Un logo pérenne doit pouvoir durer au-delà des tendances graphiques passagères.',
    category: 'Logo',
    challengeType: 'Vrai/Faux',
    tags: ['socle', 'défi', 'vrai ou faux'],
  }),
  baseChallenge({
    id: 'APPROVED-VRAIFAUX-008',
    question: 'Deux couleurs complémentaires sont placées côte à côte sur le cercle chromatique.',
    answer: 'Faux',
    wrongAnswers: ['Vrai'],
    explanation: "Deux couleurs complémentaires se trouvent à l'opposé l'une de l'autre sur le cercle chromatique.",
    category: 'Signe et couleur',
    challengeType: 'Vrai/Faux',
    tags: ['socle', 'défi', 'vrai ou faux'],
  }),

  baseChallenge({
    id: 'APPROVED-CHIFFRES-001',
    question: "Donnez la valeur précise du nombre d'or.",
    answer: '1,618',
    explanation: "Le nombre d'or, aussi appelé phi, vaut environ 1,618.",
    category: 'Composition',
    challengeType: 'Chiffres',
    tags: ['livre', 'défi', 'chiffres'],
    source: bookSource,
    sourcePage: '80',
  }),
  baseChallenge({
    id: 'APPROVED-CHIFFRES-002',
    question: 'En quelle année la typographie Futura a-t-elle été créée ?',
    answer: '1927',
    explanation: 'Paul Renner a créé Futura en 1927.',
    category: 'Typographie',
    challengeType: 'Chiffres',
    tags: ['livre', 'défi', 'chiffres'],
    source: bookSource,
    sourcePage: '68',
  }),
  baseChallenge({
    id: 'APPROVED-CHIFFRES-003',
    question: 'En quelle année la typographie Helvetica a-t-elle été créée ?',
    answer: '1957',
    explanation: 'Max Miedinger a créé Neue Haas Grotesk, ensuite renommée Helvetica, en 1957.',
    category: 'Typographie',
    challengeType: 'Chiffres',
    tags: ['livre', 'défi', 'chiffres'],
    source: bookSource,
    sourcePage: '69',
  }),
  baseChallenge({
    id: 'APPROVED-CHIFFRES-004',
    question: 'Combien de couleurs le cercle chromatique présenté dans le livre contient-il au total ?',
    answer: '12',
    explanation: 'Il contient 3 couleurs primaires, 3 secondaires et 6 tertiaires, soit 12 couleurs.',
    category: 'Signe et couleur',
    challengeType: 'Chiffres',
    tags: ['livre', 'défi', 'chiffres'],
    source: bookSource,
    sourcePage: '32',
  }),
  baseChallenge({
    id: 'APPROVED-CHIFFRES-005',
    question: 'Combien de bits composent un octet ?',
    answer: '8',
    explanation: 'Un octet est composé de 8 bits.',
    category: 'Production',
    challengeType: 'Chiffres',
    tags: ['livre', 'défi', 'chiffres'],
    source: bookSource,
    sourcePage: '92',
  }),
  baseChallenge({
    id: 'APPROVED-CHIFFRES-006',
    question: 'Combien de grandes phases composent la chaîne graphique présentée dans le livre ?',
    answer: '5',
    explanation: 'Les cinq phases sont la stratégie, la création, la réalisation, la finition, puis la distribution et la diffusion.',
    category: 'Production',
    challengeType: 'Chiffres',
    tags: ['livre', 'défi', 'chiffres'],
    source: bookSource,
    sourcePage: '22',
  }),
]
