import { initialQuestions } from './initialQuestions.js'

export const mockProfiles = [
  {
    id: 'lucas-preview',
    username: 'lucas',
    display_name: 'Lucas',
    role: 'Design, dev et contenu',
    avatar_url: '',
    avatar_key: 'couronne',
    accent_key: 'blue',
    accent_color: '#06C0F9',
    accent_secondary: '#0D3C4A',
  },
  {
    id: 'awen-preview',
    username: 'awen',
    display_name: 'Awen',
    role: 'Relecture, tests et équilibrage',
    avatar_url: '',
    avatar_key: 'couleur',
    accent_key: 'pink',
    accent_color: '#FF37A5',
    accent_secondary: '#4C1A35',
  },
]

const mockTestTickets = [
  {
    title: 'Expliquer la lecture des questions Quiz',
    description: "Ajouter un onboarding expliquant qu’une question Quiz doit être lue à un autre joueur. Une fois la mécanique comprise, elle fonctionne correctement.",
    test: 'Test 1',
  },
  {
    title: 'Afficher clairement « À toi de lire »',
    description: "Indiquer explicitement à la personne qui pose la question Quiz que c’est à elle de la lire, notamment pour le personnage Lucien.",
    test: 'Test 1',
  },
  {
    title: 'Rendre le tutoriel des bonus obligatoire',
    description: "Rappeler l’utilisation des bonus dans un tutoriel UI/UX obligatoire au lancement. L’onboarding initial n’a pas été vu.",
    test: 'Test 1',
  },
  {
    title: 'Mieux introduire les activités',
    description: "Avant une activité, annoncer ce qui va se passer et préciser que son contenu doit rester caché aux autres joueurs.",
    test: 'Test 1',
  },
  {
    title: 'Simplifier le lancement des bonus',
    description: "Simplifier encore le déclenchement d’un bonus afin que le joueur reste attentif aux questions des autres pendant sa préparation.",
    test: 'Test 1',
  },
  {
    title: 'Transformer la case Terminé en bureau du boss',
    description: "Renommer ou illustrer la case Terminé comme le bureau du boss.",
    test: 'Test 1',
  },
  {
    title: 'Clarifier le fonctionnement de la case Terminé',
    description: "Préciser qu’atteindre la case Terminé ne met pas immédiatement fin à la partie et qu’il faut continuer à jouer.",
    test: 'Test 1',
  },
  {
    title: 'Ajouter une fermeture claire à l’onboarding',
    description: "Ajouter une commande explicite permettant de fermer l’onboarding.",
    test: 'Test 1',
  },
  {
    title: 'Gérer les conflits entre bonus et malus',
    description: "Vérifier les conflits lorsqu’un bonus cible un joueur qui subit déjà un malus.",
    test: 'Test 1',
  },
  {
    title: 'Rendre visible le scroll des activités communes',
    description: "Renforcer l’indication visuelle montrant que le contenu d’une activité commune peut défiler.",
    test: 'Test 1',
  },
  {
    title: 'Ajouter un retour sonore ou haptique aux activités',
    description: "Ajouter un son ou une vibration au lancement d’une activité.",
    test: 'Test 1',
  },
  {
    title: 'Ajouter des défis et activités au plateau',
    description: "Augmenter la variété et le nombre de défis et d’activités disponibles sur le plateau.",
    test: 'Test 1',
  },
  {
    title: 'Préciser la règle du lancer de 6',
    description: "Indiquer clairement que lorsqu’un joueur obtient 6, il ne relance pas le dé.",
    test: 'Test 1',
  },
  {
    title: 'Renforcer le ton des messages',
    description: "Tacler davantage les joueurs avec des messages adaptés à la difficulté et envisager de faire parler le boss plutôt que l’application.",
    test: 'Test 1',
  },
  {
    title: 'Ajouter une vibration au buzzer',
    description: "Déclencher un retour haptique lors de l’utilisation du buzzer.",
    test: 'Test 1',
  },
  {
    title: 'Mieux expliquer le lore',
    description: "Présenter plus clairement l’univers, le contexte et les enjeux du jeu avant la partie.",
    test: 'Test 2',
  },
  {
    title: 'Sécuriser le lancement de la partie',
    description: "À 1 min 30, Quentin a lancé la partie trop vite. Ajouter une étape de préparation ou un compte à rebours afin que tous les joueurs soient prêts, pas seulement l’administrateur.",
    test: 'Test 2',
  },
  {
    title: 'Expliquer à qui s’adresse la question',
    description: "À 3 min 41, Joffrey n’a pas compris que la question affichée était destinée à son collègue. Ajouter une animation rapide indiquant le joueur concerné.",
    test: 'Test 2',
  },
  {
    title: 'Mettre en scène le thème de la question',
    description: "Afficher une animation de type roulette annonçant le thème tiré, avec une option pour la passer lorsque les joueurs veulent aller plus vite.",
    test: 'Test 2',
  },
  {
    title: 'Allonger la durée minimale des parties',
    description: "Rééquilibrer la progression car il est possible d’atteindre la fin en moins de vingt minutes.",
    test: 'Test 2',
  },
  {
    title: 'Mieux répartir Quiz, défis et activités',
    description: "À 15 min 14, Joffrey indique avoir rencontré uniquement des Quiz alors qu’il souhaite jouer aux autres types de contenus.",
    test: 'Test 2',
  },
  {
    title: 'Ajouter le bonus Plus ou moins 1',
    description: "Créer un bonus permettant d’ajouter ou de retirer un point au résultat.",
    test: 'Test 2',
  },
  {
    title: 'Tester le Vrai ou Faux en BO3',
    description: "Évaluer une variante où le Vrai ou Faux se joue au meilleur des trois manches.",
    test: 'Test 2',
  },
  {
    title: 'Clarifier les règles des activités communes',
    description: "Expliquer sur quoi repose l’activité commune, ce qui va se passer et comment les points sont attribués à chaque joueur.",
    test: 'Test 2',
  },
  {
    title: 'Corriger l’animation sur iOS',
    description: "Identifier et corriger le dysfonctionnement des animations observé sur iOS.",
    test: 'Test 2',
  },
  {
    title: 'Ajouter des événements en partie',
    description: "Aucun événement n’est apparu pendant le test. Vérifier leur déclenchement et leur fréquence.",
    test: 'Test 2',
  },
  {
    title: 'Augmenter la durée des parties',
    description: "La partie a été jugée trop courte. Ajuster le plateau, la progression ou la quantité de contenu.",
    test: 'Test 2',
  },
  {
    title: 'Repenser les cases Terminé et Mystère',
    description: "Clarifier la fonction et la mise en scène des cases Terminé et Mystère.",
    test: 'Test 2',
  },
  {
    title: 'Ajouter des questions de mémorisation',
    description: "Reposer certaines questions déjà jouées afin de vérifier que les réponses ont bien été retenues.",
    test: 'Test 2',
  },
  {
    title: 'Refondre la case Quiz',
    description: "Attribuer une catégorie aléatoire au joueur, lui laisser choisir uniquement la difficulté, puis gagner ou perdre autant de points que le nombre de jalons.",
    test: 'Test 2',
  },
  {
    title: 'Valoriser les personnages et leurs pouvoirs',
    description: "Faire lire les descriptions et caractéristiques des personnages et ajouter un super-pouvoir propre à chacun, dans l’esprit de Bang.",
    test: 'Test 2',
  },
  {
    title: 'Éviter les répétitions en rejouant',
    description: "Mémoriser les questions déjà utilisées dans une session afin que la fonction Rejouer évite de les proposer à nouveau.",
    test: 'Test 2',
  },
  {
    title: 'Ajouter comptes, emotes et personnalisation',
    description: "Créer un système de comptes avec emotes, options de personnalisation et éléments de gamification.",
    test: 'Test 2',
  },
  {
    title: 'Permettre de cumuler deux contrôles',
    description: "Lorsque le joueur possède deux contrôles, permettre de lancer les deux au cours de la même action.",
    test: 'Test 2',
  },
  {
    title: 'Prévoir des extensions de plateau',
    description: "Concevoir un DLC, une extension ou un nouveau plateau pour proposer des parties plus longues.",
    test: 'Test 2',
  },
  {
    title: 'Créer de vrais pions pour la direction artistique',
    description: "Concevoir des pions inspirés de Leaders et Courtisans. Utiliser les références disponibles dans Discord, forum Patchs, Izhak Test V1.",
    test: 'Test 2',
  },
  {
    title: 'Corriger les accords dans les félicitations',
    description: "Corriger les messages pour écrire « mes félicitations » avec les accords appropriés.",
    test: 'Test Valenciennes',
  },
  {
    title: 'Encourager la lecture des cartes Personnage',
    description: "Les cartes Personnage ne sont pas lues. Renforcer leur présentation ou intégrer une étape de lecture obligatoire.",
    test: 'Test Valenciennes',
  },
  {
    title: 'Corriger la forme du tag Bonus dans les activités',
    description: "Revoir la forme et l’intégration visuelle du tag Bonus dans l’événement Activité.",
    test: 'Test Valenciennes',
  },
  {
    title: 'Permettre l’ouverture de l’appareil photo',
    description: "Ajouter une action permettant d’ouvrir directement l’appareil photo depuis l’application.",
    test: 'Test Valenciennes',
  },
  {
    title: 'Allonger le temps de lecture des popups',
    description: "L’utilisateur n’a pas eu le temps de lire le popup. Adapter sa durée ou laisser sa fermeture au joueur.",
    test: 'Test Valenciennes',
  },
  {
    title: 'Ajouter du motion design à l’onboarding',
    description: "Ajouter des animations utiles à l’onboarding afin de mieux guider l’attention et la compréhension.",
    test: 'Test Valenciennes',
  },
].map((ticket, index) => ({
  id: `LCG-${String(index + 13).padStart(2, '0')}`,
  title: ticket.title,
  description: `${ticket.description}\n\n${ticket.test}`,
  status: 'Backlog',
  owner: 'Lucas',
  ownerId: 'lucas-preview',
  priority: 'Moyenne',
  source: 'Test Iz & Val',
  tag: '',
  tags: [],
  due: 'À cadrer',
  feature: 'Playtests',
  objective: '',
  risk: '',
  validation: '',
}))
const mockRoadmapTickets = [
  // Source: Sheet POC vs V1
  {
    source: 'Sheet POC vs V1',
    title: 'Adapter le jeu pour 3 à 7 joueurs',
    description: 'Faire évoluer le format actuel prévu pour quatre joueurs afin de prendre correctement en charge les parties de trois à sept joueurs.',
    feature: 'Backlog / Kanban',
  },
  {
    source: 'Sheet POC vs V1',
    title: 'Déployer un onboarding animé',
    description: 'Ajouter un onboarding au début du jeu et avant les activités, avec de courtes animations pour guider la compréhension.',
    feature: 'Navigation / UI',
  },
  {
    source: 'Sheet POC vs V1',
    title: 'Ajouter un espace de commentaires utilisateurs',
    description: 'Créer un espace de feedback permettant aux utilisateurs de laisser et consulter des commentaires.',
    feature: 'Navigation / UI',
  },
  {
    source: 'Sheet POC vs V1',
    title: 'Refondre l’interface avec la direction artistique',
    description: 'Concevoir une interface plus aboutie intégrant pleinement la direction artistique et une meilleure expérience UI/UX.',
    feature: 'Navigation / UI',
  },
  {
    source: 'Sheet POC vs V1',
    title: 'Rendre le jeu multilingue',
    description: 'Prévoir une version française et anglaise de l’interface, des règles et des contenus du jeu.',
    feature: 'Navigation / UI',
  },
  {
    source: 'Sheet POC vs V1',
    title: 'Créer un minijeu quotidien',
    description: 'Imaginer un minijeu quotidien engageant, inspiré des expériences LinkedIn et des April Fools de Figma.',
    feature: 'Backlog / Kanban',
  },
  {
    source: 'Sheet POC vs V1',
    title: 'Ajouter une progression des personnages',
    description: 'Créer des raretés, des personnages déblocables avec des points et des compétences inspirées de leur profil ou de leur CV.',
    feature: 'Comptes',
  },
  {
    source: 'Sheet POC vs V1',
    title: 'Créer une version entièrement numérique',
    description: 'Concevoir un mode de jeu complet utilisable sans plateau physique.',
    feature: 'Navigation / UI',
  },
  {
    source: 'Sheet POC vs V1',
    title: 'Permettre la création d’un compte',
    description: 'Ajouter le parcours de création et d’initialisation d’un compte joueur.',
    feature: 'Comptes',
  },
  {
    source: 'Sheet POC vs V1',
    title: 'Ajouter un historique des parties',
    description: 'Conserver et afficher les parties jouées, leurs résultats et leurs informations principales.',
    feature: 'Comptes',
  },
  {
    source: 'Sheet POC vs V1',
    title: 'Créer une liste d’amis',
    description: 'Permettre d’ajouter des amis et de les inviter directement dans une partie.',
    feature: 'Comptes',
  },
  {
    source: 'Sheet POC vs V1',
    title: 'Mettre en place la base de données',
    description: 'Définir puis implémenter le modèle de données nécessaire aux comptes, parties, questions et interactions.',
    feature: 'Mock data',
  },
  {
    source: 'Sheet POC vs V1',
    title: 'Créer un backoffice de questions',
    description: 'Fournir une interface interne rapide pour ajouter, modifier et organiser les questions.',
    feature: 'Question Studio',
  },
  {
    source: 'Sheet POC vs V1',
    title: 'Créer le site et les réseaux sociaux',
    description: 'Préparer la présence publique du jeu avec un site internet et les contenus nécessaires aux réseaux sociaux.',
    feature: 'Navigation / UI',
  },
  {
    source: 'Sheet POC vs V1',
    title: 'Concevoir une version solo',
    description: 'Adapter les règles et les interactions pour permettre de jouer seul.',
    feature: 'Backlog / Kanban',
  },
  {
    source: 'Sheet POC vs V1',
    title: 'Concevoir une version duo',
    description: 'Adapter les règles, le rythme et l’équilibrage pour une partie à deux joueurs.',
    feature: 'Backlog / Kanban',
  },
  {
    source: 'Sheet POC vs V1',
    title: 'Décliner les durées de partie',
    description: 'Proposer des versions rapide et longue, ainsi que des extensions ou DLC pour enrichir les parties.',
    feature: 'Backlog / Kanban',
  },
  {
    source: 'Sheet POC vs V1',
    title: 'Permettre la création de parties personnalisées',
    description: 'Laisser l’utilisateur choisir les catégories de questions et leur pourcentage d’apparition.',
    feature: 'Backlog / Kanban',
  },

  // Source: Moi
  {
    source: 'Moi',
    title: 'Uniformiser la taille des personnages',
    description: 'Remettre tous les personnages à la même taille dans l’ensemble de l’interface.',
    feature: 'Navigation / UI',
  },
  {
    source: 'Moi',
    title: 'Appliquer de vrais clip-path aux angles',
    description: 'Créer une découpe cohérente et réutilisable sur tous les angles concernés de l’application.',
    feature: 'Navigation / UI',
  },
  {
    source: 'Moi',
    title: 'Transformer le projet en application installable',
    description: 'Étudier et mettre en place la solution adaptée pour distribuer le projet comme une véritable application.',
    feature: 'Navigation / UI',
  },
  {
    source: 'Moi',
    title: 'Prévoir une alternative responsive en hauteur',
    description: 'Adapter les écrans aux faibles hauteurs disponibles, en plus du responsive basé sur la largeur.',
    feature: 'Navigation / UI',
  },
  {
    source: 'Moi',
    title: 'Nettoyer le code et formaliser le design system',
    description: 'Reprendre le code progressivement et construire un design system complet, cohérent et maintenable.',
    feature: 'Navigation / UI',
  },

  // Source: Codex - App
  {
    source: 'Codex',
    title: 'Ajouter un onboarding global au lancement',
    description: 'Demander « As-tu déjà joué ? » au lancement et afficher une explication courte lorsque la réponse est non.',
    feature: 'Navigation / UI',
  },
  {
    source: 'Codex',
    title: 'Expliquer le rangement du premier bonus',
    description: 'Lors du premier bonus obtenu, indiquer clairement où le joueur peut ensuite retrouver ses bonus.',
    feature: 'Navigation / UI',
  },
  {
    source: 'Codex',
    title: 'Gérer le café du boss avec un malus existant',
    description: 'Améliorer le cas « Va faire le café du boss » lorsqu’une cible possède déjà un malus.',
    feature: 'Navigation / UI',
  },
  {
    source: 'Codex',
    title: 'Corriger le décalage vertical du Buzzer',
    description: 'Corriger le décalage vertical de l’écran lecteur du Buzzer ou documenter son report en V2.',
    feature: 'Navigation / UI',
  },
  {
    source: 'Codex',
    title: 'Vérifier le bouton « J’ai fini »',
    description: 'Tester manuellement le bouton « J’ai fini » dans l’activité commune et confirmer son comportement.',
    feature: 'Playtests',
  },
  {
    source: 'Codex',
    title: 'Intégrer le véritable visuel du boss',
    description: 'Utiliser le SVG et la couleur définitifs du boss dans le feedback d’égalité de l’activité commune.',
    feature: 'Navigation / UI',
  },
  {
    source: 'Codex',
    title: 'Vérifier la popup « bureau du boss à portée »',
    description: 'Contrôler sa durée, sa fermeture et le moment exact auquel elle apparaît.',
    feature: 'Playtests',
  },
  {
    source: 'Codex',
    title: 'Clarifier les notes sur les popups boss',
    description: 'Retrouver et clarifier l’ancienne note concernant les popups boss et le comportement de CTRL + Z.',
    feature: 'Navigation / UI',
  },

  // Source: Codex - Questions et contenus
  {
    source: 'Codex',
    title: 'Intégrer l’export de questions expertes',
    description: 'Importer le nouvel export de questions expertes dans la source de contenu du jeu.',
    feature: 'Question Studio',
  },
  {
    source: 'Codex',
    title: 'Vérifier la distribution des questions',
    description: 'Contrôler la répartition des questions par catégorie et difficulté après l’import.',
    feature: 'Question Studio',
  },
  {
    source: 'Codex',
    title: 'Corriger le test content_selection',
    description: 'Mettre à jour le test qui attend encore 162 questions alors que quiz.json en contient désormais 158.',
    feature: 'Question Studio',
  },
  {
    source: 'Codex',
    title: 'Retrouver les wordings des événements',
    description: 'Fournir ou retrouver l’extrait précis des textes d’événements avant une nouvelle passe éditoriale.',
    feature: 'Question Studio',
  },

  // Source: Codex - Tests manuels
  {
    source: 'Codex',
    title: 'Tester le jeu sur des mobiles réels',
    description: 'Effectuer un test complet sur un iPhone et un appareil Android physiques.',
    feature: 'Playtests',
  },
  {
    source: 'Codex',
    title: 'Repasser la checklist iOS Safari',
    description: 'Vérifier de nouveau tous les points responsive et interactifs dans Safari sur iOS.',
    feature: 'Playtests',
  },
  {
    source: 'Codex',
    title: 'Rechecker les écrans d’activité commune',
    description: 'Revalider les écrans de brief, création, upload, vote et révélation de l’activité commune.',
    feature: 'Playtests',
  },
  {
    source: 'Codex',
    title: 'Surveiller l’apparition du bureau du boss',
    description: 'Garder sous surveillance le cas où le bureau du boss devient accessible trop tôt, même si les derniers faux tests ne le reproduisent pas.',
    feature: 'Playtests',
  },

  // Source: Codex - Technique et release
  {
    source: 'Codex',
    title: 'Revalider le lint du client',
    description: 'Relancer le lint client et traiter les erreurs encore signalées par l’ancien suivi.',
    feature: 'Navigation / UI',
  },
  {
    source: 'Codex',
    title: 'Revalider les audits npm',
    description: 'Exécuter npm audit à la racine et dans le client avant toute publication publique.',
    feature: 'Navigation / UI',
  },
  {
    source: 'Codex',
    title: 'Trier les fichiers non suivis',
    description: 'Examiner les fichiers non suivis et décider lesquels garder ou committer, notamment les imports POC et questions.',
    feature: 'Mock data',
  },
].map((ticket, index) => ({
  id: 'LCG-' + String(index + 55).padStart(2, '0'),
  title: ticket.title,
  description: ticket.description,
  status: 'Backlog',
  owner: 'Lucas',
  ownerId: 'lucas-preview',
  priority: 'Moyenne',
  source: ticket.source,
  tag: '',
  tags: [],
  due: 'Sans échéance',
  feature: ticket.feature,
  objective: '',
  risk: '',
  validation: '',
}))

export const mockBacklog = [
  ...mockTestTickets,
  ...mockRoadmapTickets,
]

export const mockPlaytests = [
  {
    id: 'PT-04',
    date: '2026-09-03',
    status: 'Analysée',
    prototype: 'Build papier 0.2',
    facilitatorId: 'lucas-preview',
    participants: ['Lucas', 'Awen', 'Clara', 'Mehdi'],
    duration: '42 min',
    scenario: 'Partie complète à 4 joueurs avec focus sur les défis et le scoring final.',
    scores: { rythme: 4, clarte: 3, tension: 4, plaisir: 4 },
    sentiment: 'Bon rythme général, fin de partie tendue mais scoring encore trop expliqué à l’oral.',
    learnings: [
      'Les joueurs comprennent vite les familles de questions quand les pictos sont visibles.',
      'Le calcul final ralentit la table après le dernier défi.',
      'Les cartes Défi créent de bons pics d’attention mais arrivent un peu tard.',
    ],
    issues: ['Scoring final flou', 'Défis trop espacés'],
    decisions: ['Tester un rappel de scoring imprimé sur l’aide de jeu.'],
    nextActions: ['Réécrire la séquence de fin', 'Ajouter 4 défis faciles au paquet de départ'],
    relatedTicketIds: [],
    driveUrl: 'https://drive.google.com/',
  },
  {
    id: 'PT-05',
    date: '2026-09-06',
    status: 'À analyser',
    prototype: 'Build duo 0.2.1',
    facilitatorId: 'awen-preview',
    participants: ['Lucas', 'Awen'],
    duration: '28 min',
    scenario: 'Test rapide en duo pour mesurer la densité des défis et l’équilibre des difficultés.',
    scores: { rythme: 5, clarte: 4, tension: 3, plaisir: 4 },
    sentiment: 'Format plus nerveux, difficulté mieux répartie, mais les choix de duel manquent d’impact.',
    learnings: [
      'Les questions faciles sécurisent mieux l’entrée de partie.',
      'Les duels gagnent à être déclenchés par une vraie prise de risque.',
    ],
    issues: ['Choix de duel peu coûteux', 'Manque de questions production faciles'],
    decisions: [],
    nextActions: ['Prototyper une pénalité légère en duel'],
    relatedTicketIds: [],
    driveUrl: 'https://drive.google.com/',
  },
  {
    id: 'PT-06',
    date: '2026-09-11',
    status: 'Planifiée',
    prototype: 'Build atelier 0.3',
    facilitatorId: 'lucas-preview',
    participants: ['Lucas', 'Awen', 'Nina', 'Yanis', 'Samir'],
    duration: '60 min',
    scenario: 'Première partie avec joueurs externes : onboarding, lisibilité des catégories, durée réelle.',
    scores: { rythme: null, clarte: null, tension: null, plaisir: null },
    sentiment: 'À observer : autonomie des joueurs après lecture des règles courtes.',
    learnings: [],
    issues: ['Règles non validées', 'Matériel à imprimer'],
    decisions: [],
    nextActions: ['Imprimer aide de jeu', 'Préparer grille d’observation'],
    relatedTicketIds: [],
    driveUrl: 'https://drive.google.com/',
  },
]
export const mockWorklog = [
  {
    id: 'WL-108',
    date: '2026-09-08',
    author: 'Lucas',
    authorId: 'lucas-preview',
    type: 'Développement',
    module: 'Worklog',
    effortMinutes: 95,
    summary: 'Transformation du Worklog en journal de production filtrable.',
    decision: 'Conserver le Worklog en données mock locales tant que le schéma Supabase projet n’est pas figé.',
    decisionStatus: 'open',
    blocker: '',
    blockerStatus: 'none',
    nextAction: 'Relire la vue avec Awen et valider les champs nécessaires au vrai modèle de données.',
  },
  {
    id: 'WL-107',
    date: '2026-09-07',
    author: 'Lucas',
    authorId: 'lucas-preview',
    type: 'Architecture',
    module: 'Backlog',
    effortMinutes: 130,
    summary: 'Séparation du backlog, des playtests et du Question Studio en modules de navigation.',
    decision: 'Le backlog/kanban reste l’écran d’accueil du Studio.',
    decisionStatus: 'treated',
    blocker: '',
    blockerStatus: 'none',
    nextAction: 'Stabiliser les actions rapides avant branchement persistant.',
  },
  {
    id: 'WL-106',
    date: '2026-09-06',
    author: 'Awen',
    authorId: 'awen-preview',
    type: 'Playtest',
    module: 'Playtests',
    effortMinutes: 60,
    summary: 'Analyse du test duo rapide et extraction des problèmes de rythme.',
    decision: 'Augmenter la fréquence des défis dans le prochain prototype.',
    decisionStatus: 'open',
    blocker: 'Les notes de session ne sont pas encore reliées aux tickets.',
    blockerStatus: 'open',
    nextAction: 'Créer un ticket par retour joueur exploitable.',
  },
  {
    id: 'WL-105',
    date: '2026-09-05',
    author: 'Lucas',
    authorId: 'lucas-preview',
    type: 'Contenu',
    module: 'Question Studio',
    effortMinutes: 85,
    summary: 'Nettoyage des exports quiz et duels, avec vérification des questions validées.',
    decision: '',
    decisionStatus: 'none',
    blocker: 'Certaines questions importées restent trop proches de la source.',
    blockerStatus: 'open',
    nextAction: 'Réécrire les formulations signalées en révision.',
  },
  {
    id: 'WL-104',
    date: '2026-09-03',
    author: 'Awen',
    authorId: 'awen-preview',
    type: 'UX',
    module: 'Studio',
    effortMinutes: 70,
    summary: 'Passe UI sobre pour densifier les écrans projet sans les transformer en dashboard décoratif.',
    decision: 'Prioriser les vues de travail compactes plutôt que des cartes statistiques isolées.',
    decisionStatus: 'treated',
    blocker: '',
    blockerStatus: 'none',
    nextAction: 'Vérifier les écrans module par module sur mobile.',
  },
  {
    id: 'WL-103',
    date: '2026-06-14',
    author: 'Lucas',
    authorId: 'lucas-preview',
    type: 'Développement',
    module: 'Question Studio',
    effortMinutes: 180,
    summary: 'Création du Question Studio avec validations Lucas/Awen, commentaires et export JSON.',
    decision: 'Deux validations sont nécessaires avant export vers le jeu.',
    decisionStatus: 'treated',
    blocker: '',
    blockerStatus: 'none',
    nextAction: 'Préparer l’import de questions depuis les sources pédagogiques.',
  },
]
export const mockIdeas = [
  {
    id: 'IDEA-01',
    title: 'Le boss commente la partie',
    content: 'Faire intervenir le boss entre deux tours avec des remarques courtes liées à ce qui vient de se passer.',
    colorKey: 'red',
    pinned: true,
    createdAt: '2026-09-10T10:15:00.000Z',
    updatedAt: '2026-09-10T10:15:00.000Z',
  },
  {
    id: 'IDEA-02',
    title: 'Défi typographique express',
    content: 'Un joueur doit reconnaître une typographie ou corriger une composition en moins de trente secondes.',
    colorKey: 'yellow',
    pinned: true,
    createdAt: '2026-09-09T14:30:00.000Z',
    updatedAt: '2026-09-09T14:30:00.000Z',
  },
  {
    id: 'IDEA-03',
    title: 'Souvenir de partie partageable',
    content: 'Générer une petite carte récapitulative avec le personnage, le score et le meilleur moment de la partie.',
    colorKey: 'blue',
    pinned: false,
    createdAt: '2026-09-08T09:20:00.000Z',
    updatedAt: '2026-09-08T09:20:00.000Z',
  },
  {
    id: 'IDEA-04',
    title: 'Événements selon le lieu',
    content: 'Imaginer des événements différents selon que la partie se déroule en école, en agence ou à distance.',
    colorKey: 'green',
    pinned: false,
    createdAt: '2026-09-07T16:45:00.000Z',
    updatedAt: '2026-09-07T16:45:00.000Z',
  },
]

export function createMockWorkspace() {
  const profiles = mockProfiles.map((profile) => ({ ...profile }))
  const currentProfile = profiles[0]
  const firstQuestionId = initialQuestions[0]?.id
  const approvals = initialQuestions.flatMap((question) =>
    (question.approvals || []).map((approval) => ({
      question_id: question.id,
      reviewer_id: reviewerId(approval.reviewer),
      created_at: approval.at,
    })),
  )

  return {
    profiles,
    profile: currentProfile,
    session: { user: { id: currentProfile.id } },
    approvals,
    comments: firstQuestionId
      ? [{
          id: 1,
          question_id: firstQuestionId,
          author_id: 'awen-preview',
          body: '@Lucas je trouve la formulation plus claire comme ça.',
          created_at: new Date().toISOString(),
        }]
      : [],
    exports: [
      {
        id: 'EXP-003',
        kind: 'quiz',
        question_count: 0,
        created_by: 'lucas-preview',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
      },
      {
        id: 'EXP-002',
        kind: 'duels',
        question_count: 0,
        created_by: 'awen-preview',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
      },
    ],
    backlog: mockBacklog.map((ticket) => ({ ...ticket })),
    ideas: mockIdeas.map((idea) => ({ ...idea })),
    playtests: mockPlaytests.map((playtest) => ({ ...playtest })),
    worklog: mockWorklog.map((entry) => ({ ...entry })),
    questionRows: initialQuestions.map(toQuestionRow),
  }
}

function reviewerId(name) {
  return name === 'Lucas' ? 'lucas-preview' : 'awen-preview'
}

function toQuestionRow(question) {
  return {
    id: question.id,
    question: question.question,
    answer: question.answer,
    wrong_answers: [...(question.wrongAnswers || [])],
    explanation: question.explanation,
    category: question.category,
    difficulty: question.difficulty,
    milestones: question.milestones,
    mode: question.mode,
    challenge_type: question.challengeType,
    status: question.status,
    tags: [...(question.tags || [])],
    source: question.source,
    source_page: question.sourcePage,
    revision_notes: question.revisionNotes,
    favorite: question.favorite,
    confidence: question.confidence,
    version: 1,
    last_exported_version: null,
    last_exported_at: null,
    deleted_at: null,
    created_by: 'lucas-preview',
    updated_by: 'lucas-preview',
    created_at: question.createdAt,
    updated_at: question.updatedAt,
  }
}
